### ISSUE TITLE
Värde eller trend på parametersök - väsentligt att ha med?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#100]
Vad jag kan se är varken värde eller trend med på vattensidan, behöver vi ha med denna i söket?

![image](https://cloud.githubusercontent.com/assets/11041042/7064193/e9f49588-deac-11e4-8fd2-5f0b7b1a687d.png)

**Comment by idaber** [comment]
Verkar finnas på några få parameterar, behöver man visa dessa då?eller kan man mörklägga den ex. när det inte finns val att göra i scrollistorna?

**Comment by victor--** [comment]
Ett alternativ är att visa antalet möjliga val som en räknare till höger om rubriken för dropdownlistorna. Då kan man i alla fall se om man kan välja något utan att behöva klicka på dem. Detta får bli ett annat ärende i så fall, tycker jag. Sätter WONTFIX

**Comment by idaber** [comment]
ok
