### ISSUE TITLE
grafiska på åtgärdssöket

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#101]
Ny färg kanske?

http://develop.vattenmyndigheten.local/Search.aspx?searchType=Measures

![image](https://cloud.githubusercontent.com/assets/11041042/7064545/d144cdca-deaf-11e4-9825-c5a56f1fdb2a.png)

**Comment by victor--** [comment]
Detta är åtgärdat iom nya åtgärdsexporten
