### ISSUE TITLE
Listning visar fler sökresultat än filtrering i Bedömningar på vattensöket

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#102]
Söker på Kalmar län och parameter Miljögifter, varför får jag fram resterande parameter på samma sjöar när jag valt miljögifter?

![image](https://cloud.githubusercontent.com/assets/11041042/7065760/51611ff8-debb-11e4-850c-07232e09aa0c.png)

**Comment by idaber** [comment]
http://develop.vattenmyndigheten.local/Search.aspx?searchType=WaterMotivations&SearchOnLoad=true&LockWaterDataset=&waterTypeID=36&parameterSearchType=4&freeTextSearch=&WaterDataSet=2&ReportUnitSearch=128&SearchAfterDate=&SearchBeforeDate=&countryID=&competentAuthorityID=&areaID=&countyID=2&municipalityID=-&basinID=&subUnitID_2=&subUnitID_8=&subUnitID_1=&subUnitID_4=&protectedAreaCategoryID=&SearchResponsibleCounty=1&userID=&measureSurfaceWaterPressureTypeID=&swpressureparameterClassificationID=&measureSurfaceWaterImpactTypeID=&swimpactparameterClassificationID=&measuresEcosystemDependingImpactTypeID=&ecoimpactparameterClassificationID=&WaterParameterClassificationMotivationConfidenceIndicatorID=&WaterParameterClassificationMotivationTypeID=1&parameterGroupID=244&parameterID=485&parameterClassificationID=&parameterValueID=&parameterVersionID=&waterParameterClassificationTrend=&extraParametersSearchOption=0&DialogMode=&DoSearch=&SortType=1&ReversSort=false&requirePermissionsToSelect=false&searchLockAreas=false&searchLockBasins=false&searchLockMunicipality=false&searchLockWaterType=false&AssociatedWaters=&postbackAction=&searchLockReportUnitSearchTypes=

**Comment by victor--** [comment]
"Fixat" genom att ändra Parameterrubriken i sökresultatet till titeln på det aktiva sökvalet

**Comment by idaber** [comment]
gött mos :-)

**Comment by idaber** [comment]
Den här verkar inte vara ändrad?

![image](https://cloud.githubusercontent.com/assets/11041042/7346633/9c249e74-ece0-11e4-8f40-71b1a3940f4c.png)

**Comment by idaber** [comment]
stänger
