### ISSUE TITLE
Filter för påverkan och miljöproblem inte konsekvent mot resterande underliggande scrollistor

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#103]
kan man lägga den ens bredvid? Om inte kan vi tydliggöra att de hör ihop?

![image](https://cloud.githubusercontent.com/assets/11041042/7065818/18ad293a-debc-11e4-84a0-f7904332a82b.png)

http://develop.vattenmyndigheten.local/Search.aspx?searchType=WaterMotivations&waterTypeID=36&parameterSearchType=4

**Comment by victor--** [comment]
Absolut. Det var en gammal layoutbugg som jag aldrig fixade då jag inte valde just Sjö > Miljöproblem - Ytvatten under mitt omdesignande.

Om du hittar något mer fall där layouten blir på samma sätt får du gärna flagga för det :)

**Comment by idaber** [comment]
perfa!
