### ISSUE TITLE
Import felmeddelande

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#107]
Jag blir lite förvirrad här, har min import importerats eller är det fortfarande fel på den? Kan vi ta bort den röda texten om importen är ok och bara behålla "Inga fel eller varningar hittades"?

![image](https://cloud.githubusercontent.com/assets/11041042/7112627/c069d134-e1cb-11e4-9cc9-f3ef41a5d1a7.png)

http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivation

**Comment by victor--** [comment]
Detta ser ju ut som en regelrätt bugg.

Har du några steg jag kan följa för att reproducera? :)

**Comment by idaber** [comment]
Jag körde del 1 först sedan tog jag bort namnet på vattenförekomsten och då fick jag fram detta från del 2 filen, skickar filerna i slack

**Comment by victor--** [comment]
Just bedömningsimporten visade inget felmeddelande när ingenting kunde importeras. Jag har uppdaterat så man får detta utseendet när man importerar del 2-filen.

![screen shot 2015-04-13 at 13 14 59](https://cloud.githubusercontent.com/assets/8023473/7114590/20ca23e0-e1df-11e4-8f97-36d674147f4a.png)

**Comment by idaber** [comment]
ok
