### ISSUE TITLE
Schemalagda importer felmeddelande

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#108]
När jag schemalägger en import får jag inget felmeddelandemail om importen inte går igenom, trots att när jag laddar upp excelfilen och trycker schemalägg och meddelande om att jag får ett mail när importen är upplagd. Jag tror att importen kanske är ok och är inlagd om jag missar att dubbelkolla den?

http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivation

**Comment by idaber** [comment]
två dagar efter kommer mailet? trots att det görs körning varje timme

**Comment by idaber** [comment]
![image](https://cloud.githubusercontent.com/assets/11041042/7156990/a54bf3b8-e36b-11e4-92f1-d8fa9d16b73b.png)

**Comment by EsleEnoemos** [comment]
När mail kommer fram är tyvärr inte mycket jag kan göra åt...
Det har med emails "natur" att göra, tyvärr :-(
Det kan fastna i nån kö nånstans på vägen och det är inget den som skickar iväg mailet vet om eller kan göra något åt

**Comment by idaber** [comment]
ok vi stänger :-)
