### ISSUE TITLE
Importen klar - saknar design

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#109]
Jag har importerat en fil och får först detta meddelandet

![image](https://cloud.githubusercontent.com/assets/11041042/7114978/71e3cde0-e1e3-11e4-8ecb-0e2ace36c56d.png)

Jag trycker Genomför import och får denna, kanske designa om så den liknar den första? konsekvent :-)

![image](https://cloud.githubusercontent.com/assets/11041042/7114956/44abbdec-e1e3-11e4-8183-05af82cc88e6.png)

**Comment by victor--** [comment]
viss-idea skapad: https://github.com/victor--/viss-ideas/issues/4
