### ISSUE TITLE
Ser inte knapparna

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#11]
Jag står på ett vatten. Jag väljer att jag vill redigera allmän beskrivning. Jag klickar på Skapa ny. Jag väljer Lägg till referens. Jag skriver Test i titel och söker. I träfflistan som öppnas ser jag inga knappar så jag kan välja. Efter en stund ser jag att om jag scrollar i fönstret bakom ser jag knapparna. Om du jämför med IE så ser jag knapparna utan att behöva scrolla. 

![snap2297](https://cloud.githubusercontent.com/assets/5877295/6018209/4e761d42-ab95-11e4-9254-5280e4bcd55f.jpg)

**Comment by victor--** [comment]
Ökade höjden på första modalen, så referensmodalen ska nu få plats i den utan att man behöver skrolla.

**Comment by PernillaA** [comment]
ok
