### ISSUE TITLE
Mappning

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#119]
texten flyter ihop
![image](https://cloud.githubusercontent.com/assets/11041042/7197864/54ba3ee2-e4e6-11e4-8dce-dc8a4ed953f9.png)

http://develop.vattenmyndigheten.local/WFD2016.Mappings/#path=SWB/SurfaceWaterBody/NaturalAWBHMWB

**Comment by idaber** [comment]
Kolla du på denna?

**Comment by victor--** [comment]
Absolut. Vilken webbläsare är drabbad?

**Comment by idaber** [comment]
chrome

**Comment by victor--** [comment]
Danke! Ska vara fixat nu :)

**Comment by idaber** [comment]
Gött!
