### ISSUE TITLE
Flera vattenkategorier - grundvatten exporter

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#120]
I vilket syfte vill vi kunna välja annan vattenkategorie än Grundvatten på denna export?

![image](https://cloud.githubusercontent.com/assets/11041042/7249180/d89530ca-e818-11e4-8950-ba9d667a619a.png)

![image](https://cloud.githubusercontent.com/assets/11041042/7249222/32234744-e819-11e4-9c54-6f9e4a94c7bb.png)

http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=2&export=ExportPluginsExportPluginsWaterExportsGWImpactExport

**Comment by idaber** [comment]
Likaså på denna?

![image](https://cloud.githubusercontent.com/assets/11041042/7251830/1e2d8bd0-e82f-11e4-8803-f58e580cbb30.png)

**Comment by EsleEnoemos** [comment]
Enda syftet är att du vill kunna få ut de "klassningar" som finns på de andra vattenkategorierna.
Om allt står rätt till så borde det (tycker jag) inte finnas några, men det är helt och hållet en inställning som görs inne i admin... så det är tyvärr inte något vi kan styra över kodmässigt.
http://develop.vattenmyndigheten.local/Admin/Default.aspx?section=WaterTypes&waterTypeID=38&WaterOrStation=6

**Comment by idaber** [comment]
ok :-)
