### ISSUE TITLE
Saknar vattenkategorikolumn

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#127]
Den här gjordes i två olika etapper, då det blev ett tillägg på CoA - det sista kom inte med verkar det som

![image](https://cloud.githubusercontent.com/assets/11041042/7345161/72a414ac-ecd2-11e4-8e86-618074f9971f.png)

**Comment by idaber** [comment]
kollar du på denna sen @victor--  när du har möjlighet?

**Comment by victor--** [comment]
@idaber hoppsan, det stämmer. jag har fixat så din miljö ska ha med även det senaste tillägget :)

håller på att byggas nu, så prova om typ två minuter.

**Comment by idaber** [comment]
Tack ☺

Från: Victor Olsson [mailto:notifications@github.com]
Skickat: den 27 april 2015 11:58
Till: victor--/viss-bugs
Kopia: Ida Bergkvist
Ämne: Re: [viss-bugs] Saknar vattenkategorikolumn (#127)


@idaber<https://github.com/idaber> hoppsan, det stämmer. jag har fixat så din miljö ska ha med även det senaste tillägget :)

håller på att byggas nu, så prova om typ två minuter.

**Comment by idaber** [comment]
funkar :-)
