### ISSUE TITLE
Annuitetsvärden - importera fil

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#129]
Är det hårtkodat när man ska ladda upp fil: Browse/Välj/Bläddra? 

IE VM ware
![image](https://cloud.githubusercontent.com/assets/11041042/7648817/531b5244-fae7-11e4-99c5-22a16e686110.png)

IE 11:
![image](https://cloud.githubusercontent.com/assets/11041042/7648876/fe9ac2e4-fae7-11e4-97ef-156fa18da2ac.png)

i Chrome:
![image](https://cloud.githubusercontent.com/assets/11041042/7648827/68015b04-fae7-11e4-99e6-328bbef8d998.png)

**Comment by EsleEnoemos** [comment]
Vad det står på bläddra-knappen menar du?
Svar ja... det är webbläsaren som bestämmer, så det är inget jag kan göra nåt åt...
Skulle tro att du kan ändra den översta (Browse) till något annat om du byter språk i webbläsaren, men det går inte att välja vad det ska stå där...

**Comment by idaber** [comment]
ok misstänkte det, stänger detta :-)
