### ISSUE TITLE
Mappning Monetoringschema visar värden som inte finns

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#131]
Finns inget program som har denna inmatning:
 <ProgrammeNameNL>dasds</ProgrammeNameNL>
http://develop.vattenmyndigheten.local/WFD2016.DataInput/?areas=4
![image](https://cloud.githubusercontent.com/assets/11041042/7650606/7e40017a-faf8-11e4-897b-48c0455a345c.png)

![image](https://cloud.githubusercontent.com/assets/11041042/7650627/b0eacd8a-faf8-11e4-96de-f75135980ac4.png)

kan det vara ett raderat program som saknar titel som ligger kvar?

**Comment by idaber** [comment]
Det verkar vara så, tar jag bort inmatningen i  EUprogramCode och MSprogramCode och sparar om programmet får jag ut dessa ändå i XMLfilerna, jag ser dem dock inte trädstrukturen så kan därför inte redigera dem eller ta bort programmet igen

![image](https://cloud.githubusercontent.com/assets/11041042/7650804/5a627c7c-fafa-11e4-99a6-74fbf248ac14.png)

![image](https://cloud.githubusercontent.com/assets/11041042/7650812/69c1450e-fafa-11e4-862f-a64501b4b7cc.png)

**Comment by idaber** [comment]
Vi gör om pappa/barn funktionen så att man måste göra pappan innan barnen så ska detta inte uppstå.

**Comment by EsleEnoemos** [comment]
Men... mamma då...?
Är det ingen som tänker på henne :-(

**Comment by idaber** [comment]
ok stänger
