### ISSUE TITLE
Mappning SWMET kan inte importera fil

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#132]
Jag la till Ida manuellt och sedan valde jag att exportera filen, la till en rad med data igen och försökte importera, händer inget

![image](https://cloud.githubusercontent.com/assets/11041042/7651434/a9b3599e-fb00-11e4-9f4d-370b407766ba.png)

![image](https://cloud.githubusercontent.com/assets/11041042/7651414/711329c0-fb00-11e4-88a4-1d7c62738ba6.png)

**Comment by idaber** [comment]
fil finns i slack

**Comment by EsleEnoemos** [comment]
Det beror på vilken "nod" du står på när du gör importen...
Om du står på Ida-noden så kommer den enbart att ta den första raden i importfilen och ersätta dina värde med dessa värden.
Om du står på PercentageBQR-noden så kommer den ta samtliga poster i filen och lägga till dessa som nya noder
Inte speciellt tydligt... men så är det...

**Comment by idaber** [comment]
Jag tänker bara så de är med på att för att kunna importera flera så behöver dem klicka på pluset och samtliga fält behöver vara tomma för att importen inte ska skriva över befintliga. Så länge de bara använder importen borde det inte vara några problem. Kan ju bli tråkigt om någon lagt in data manuellt och sedan gör någon en import. Låter den vara till hösten :-)
