### ISSUE TITLE
Åtgärder

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#133]
Avrundar till tre decimaler på testkostnader
och två decimaler på årskostnadsvärde
ska vi inte vara konsekventa?
![image](https://cloud.githubusercontent.com/assets/11041042/7812181/49685388-03b0-11e5-835c-06d6b231a702.png)
http://develop.vattenmyndigheten.local/Measures/EditMeasure.aspx?measureEUID=VISSMEASURE0128740&timeStamp=635682457160573420

**Comment by idaber** [comment]
![image](https://cloud.githubusercontent.com/assets/11041042/7812234/c2cc3898-03b0-11e5-9261-072aeb0a0002.png)

**Comment by idaber** [comment]
![image](https://cloud.githubusercontent.com/assets/11041042/7812375/e819e946-03b1-11e5-8c64-36d0d2aee7fd.png)

**Comment by EsleEnoemos** [comment]
Kolla dina inställningar... :-)
