### ISSUE TITLE
Ska de skyddade områden vara länkade?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#137]
![image](https://cloud.githubusercontent.com/assets/11041042/7984859/6e56bf7c-0acc-11e5-8df8-8b08d8b55376.png)

http://develop.vattenmyndigheten.local/Stations.aspx?stationEUID=SE666666-666666

**Comment by EsleEnoemos** [comment]
Klart dom ska :-)

**Comment by idaber** [comment]
Ok fixar du det d� ??

Skickat fr�n min iPhone

5 jun 2015 kl. 15:22 skrev EsleEnoemos <notifications@github.com<mailto:notifications@github.com>>:


Klart dom ska :-)

-

**Comment by EsleEnoemos** [comment]
Redan klart

**Comment by idaber** [comment]
G�tt ??

Skickat fr�n min iPhone

5 jun 2015 kl. 15:24 skrev EsleEnoemos <notifications@github.com<mailto:notifications@github.com>>:


Redan klart

-

**Comment by EsleEnoemos** [comment]
Är inte du ledig…?

**Comment by idaber** [comment]
M�ste ju kolla s� ni jobbar p� ??...

Skickat fr�n min iPhone

5 jun 2015 kl. 15:26 skrev EsleEnoemos <notifications@github.com<mailto:notifications@github.com>>:

�r inte du ledig...?

**Comment by idaber** [comment]
ok
