### ISSUE TITLE
Sökfilter för dessa stationsparametrar på stationsexporterna.

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#139]
kan du kolla varför jag inte kan använda funktionen?

**Comment by EsleEnoemos** [comment]
Ida, Ida, Ida...
Egentligen skulle jag inte fixa det åt dig, men jag är ju i grund o botten en snäll människa...
Nu fungerar det i alla fall.
Du får bonuspoäng, med chans till att vinna en gratis fotvandring till Gällivare, om du kan gissa vad felet var :-)

**Comment by idaber** [comment]
Gött nu kan man inte skapa namn på stationsparameter med mellanslag :-)
