### ISSUE TITLE
Inaktiva stationsparametrar behöver jag visa dem på programsidan?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#141]
![image](https://cloud.githubusercontent.com/assets/11041042/8034427/d2a5d152-0de7-11e5-84ea-2c36d615bce7.png)

Behöver jag visa alla stationsparametrar om jag valt att inte använda dem?

![image](https://cloud.githubusercontent.com/assets/11041042/8034449/02bb9ad4-0de8-11e5-8967-bf5e2cfc4cd8.png)

**Comment by EsleEnoemos** [comment]
Ingen som har sagt något annat... :-)

**Comment by idaber** [comment]
stänger
