### ISSUE TITLE
Borde jag inte få resultat i snurran med dessa inställningar?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#142]
http://develop.vattenmyndigheten.local/Stations.aspx?stationEUID=SE615416-172971

http://develop.vattenmyndigheten.local/WFD2016.Mappings/#path=GWMonitoring/GWMonitorings/WellSpring

http://develop.vattenmyndigheten.local/Admin/Default.aspx?section=StationUsageParameters&stationUsageParameterID=11

**Comment by EsleEnoemos** [comment]
Får du inte ut stationen alls?
Har du någon mätning som har flaggor som gör att den ska komma med ut? (typ Operativ etc)
Sedan har du en sak till som talar emot just denna station...

**Comment by idaber** [comment]
ok stänger
