### ISSUE TITLE
55538 saknar att kunna översätta vissa rubriker/text

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#143]
Redigera exporter

![image](https://cloud.githubusercontent.com/assets/11041042/8078296/0308f61e-0f5d-11e5-9087-e0d8e5ae5d44.png)

Visa indelning

![image](https://cloud.githubusercontent.com/assets/11041042/8078292/f5172c60-0f5c-11e5-9a69-eb00084428ed.png)

Filen innehåller
Ska det under det blå sträcket vara hårdkodat annars saknar även dessa möjlighet för översättning:

![image](https://cloud.githubusercontent.com/assets/11041042/8078339/4cc0dfa6-0f5d-11e5-8b19-eb5f9e8fe3ae.png)

**Comment by EsleEnoemos** [comment]
"Filen innehåller" har jag inte gjort nåt åt...
Resten är fixat, inklusive "Kommentar till schemalagd export" :-)

**Comment by idaber** [comment]
Saknar fortfarande att kunna översätta Exportera och Schemalägg exporten?

**Comment by idaber** [comment]
Den är OK men vi behöver kolla på denna:

![image](https://cloud.githubusercontent.com/assets/11041042/8103091/0ad7b6fe-1026-11e5-978d-ddc1b939418b.png)

**Comment by idaber** [comment]
ok
