### ISSUE TITLE
Grupphantering IE10+IE9 saknar knappar+övergångsvatten+tabortkryss

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#147]
![image](https://cloud.githubusercontent.com/assets/11041042/8203751/679cb94e-14e4-11e5-9fe6-78533b121b8f.png)

**Comment by idaber** [comment]
vad har hänt med checkboxarna i IE10?
![image](https://cloud.githubusercontent.com/assets/11041042/8230046/ceff9f38-15bc-11e5-8051-f55b0128eb6f.png)

**Comment by EsleEnoemos** [comment]
Visst var det vackert :-)
Var tvungen att plocka bort "padding" o sånt för att det skulle få plats...
Men jag tänker helt ärligt inte göra någonting åt IE10!!

**Comment by idaber** [comment]
ok låter den ligga kvar som förbättring :-)
