### ISSUE TITLE
Kunna logga in som användare på Säkerhetssida

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#148]
Jag är inne på säkerhet. Då visas Knapparna " Logga in som användare" och "radera användare".
Väljer jag typ av område + ett område försvinner knapparna. 

Tar jag bort mitt val Typ av område borde knapparna dyka upp igen.

![image](https://cloud.githubusercontent.com/assets/11041042/8204432/e90e4f2a-14e8-11e5-8139-90e3a6b8d8cc.png)

**Comment by EsleEnoemos** [comment]
Nu kommer knapparna tillbaka om du väljer "ingenting" i typ av område

**Comment by idaber** [comment]
ok
