### ISSUE TITLE
Visar data trots inställning på vattenmodul

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#150]
Om jag ställer inte att den bara ska visa data efter ett visst datum så ska väl inte data synas från den 18 juni?

Hänger datum ihop med "Visa typer markerade som Gamla" känns det som vi kan lägga till en avskiljare för att förtydliga att de beror av varandra?

![image](https://cloud.githubusercontent.com/assets/11041042/8276714/fd7f4e62-18b9-11e5-8d29-b91c8e3f5789.png)

**Comment by EsleEnoemos** [comment]
"Gamla" och datumval hänger inte ihop alls utan kan anges oberoende av varandra
Ska fixa visningen i nedfällt läge!

**Comment by idaber** [comment]
ok
