### ISSUE TITLE
Designen skiljer sig åt mot hur vi har det på andra ställen med Val av Vattenkategori

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#154]
Designen skiljer mot andra sök/exporter

![image](https://cloud.githubusercontent.com/assets/11041042/8300420/ea22c9f4-1984-11e5-9eb4-209b3c9d819b.png)

Bör vara så här:

![image](https://cloud.githubusercontent.com/assets/11041042/8300429/fd830f54-1984-11e5-9429-78e08eef022c.png)

**Comment by idaber** [comment]
Görs om i ärende #55397

**Comment by idaber** [comment]
Fas två - nu blev det en scrolldownmeny:

![image](https://cloud.githubusercontent.com/assets/11041042/9434288/6d5f5f56-4a3d-11e5-81a7-f50585b30099.png)

**Comment by victor--** [comment]
Stänger detta ärende och lägger upp förslaget på viss ideas: https://github.com/victor--/viss-ideas/issues/2
