### ISSUE TITLE
saknar ä i rubriken på Undersökning

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#155]
![image](https://cloud.githubusercontent.com/assets/11041042/8301967/0d64b2b6-1993-11e5-8520-7c092938e114.png)

http://develop.vattenmyndigheten.local/MonitoringPrograms.aspx?monitoringProgramID=666&tab=Surveys#tabSurveys

**Comment by EsleEnoemos** [comment]
Verkar bara va i din webbläsare...
Jag lyckas inte få det i någon annan...

**Comment by idaber** [comment]
Verkar funka nu, stänger
