### ISSUE TITLE
Qtips export - ärver varandra

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#159]
dessa tre qtips ärver varandra - ska det vara så?

![image](https://cloud.githubusercontent.com/assets/11041042/8351791/29e67296-1b30-11e5-8098-5475e19df42c.png)

http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=3&export=ExportPluginsExportPluginsStationExportsStationUsageFlagAndMonitoringWithWatersExport&qtip=true

**Comment by idaber** [comment]
Och dessa två också:

![image](https://cloud.githubusercontent.com/assets/11041042/8351822/544fd50e-1b30-11e5-9f7a-95dd28032a34.png)

**Comment by EsleEnoemos** [comment]
Detta har inget med den nya exporten att göra...
Samma fel är faktiskt levererat skarpt också, så jag tar med mig detta till ärende 55804 så slipper vi alla problem med qtips...

**Comment by idaber** [comment]
tror du ;-)... det kommer mera..

**Comment by idaber** [comment]
ok
