### ISSUE TITLE
Avancerat sök åtgärder vattenkategori - förläng fältet så det blir symetriskt med resterande

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#163]
![image](https://cloud.githubusercontent.com/assets/11041042/9110383/8eec0b50-3c3d-11e5-97f5-0dfc932f540f.png)

http://develop.vattenmyndigheten.local/Search.aspx?searchType=Measures

**Comment by victor--** [comment]
Åtgärdat iom nya åtgärdsexporten
