### ISSUE TITLE
55778	10 - bugg innehålls flik.

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#164]
Henrik har failat ärendet förra gången och jag kan inte se att detta är åtgärdat?

1. fälla in fliken pilen lappar över rullistan i fliken. lite små fult.
2. om man scrollar på sidan så följer inte scrollningen med i flikens rullista. Så är sidan i botten så borde rullistan i fliken också vara i botten.

**Comment by victor--** [comment]
Oj då, jag måste ha glömt att merga in de ändringarna till din miljö. Sorry! Fixar!

**Comment by victor--** [comment]
Nu ska pilens placering vara fixad på övervakningsprogramsidan :+1:

**Comment by idaber** [comment]
Gött!
