### ISSUE TITLE
55692 - inte samma sökresultat i snabbsök som avancerat på åtgärder

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#165]
Sökord: VISSMEASURE0243965

snabbsök:

![image](https://cloud.githubusercontent.com/assets/11041042/9129847/e7f64d24-3cdc-11e5-8ac8-21c9cbe4b376.png)

avancerat sök:

![image](https://cloud.githubusercontent.com/assets/11041042/9129879/409237d6-3cdd-11e5-9ee8-1b9a521fbb5a.png)

**Comment by victor--** [comment]
Kan med nästan 100%:ig säkerhet säga att detta beror på att samtliga åtgärder inte indexerades. Prova gärna igen med en åtgärd som dyker upp när du skriver exempelvis "sjö" :)

**Comment by idaber** [comment]
inte ok

**Comment by idaber** [comment]
ok
