### ISSUE TITLE
53987 - snabbsöket visar inget vatten - bara åtgärd?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#166]
![image](https://cloud.githubusercontent.com/assets/11041042/9129942/11efcd3e-3cde-11e5-8b15-942112326f79.png)

på avancerat sök kommer den fram när jag söker på Allgunnen och sök efter vatten:

![image](https://cloud.githubusercontent.com/assets/11041042/9129961/4ae182a4-3cde-11e5-85a5-70087f1f3941.png)

Söker jag på snabbsök på EUID får jag absolut inga resultat: SE634690-142635

![image](https://cloud.githubusercontent.com/assets/11041042/9129971/7401afba-3cde-11e5-87b0-8e41e55d5e20.png)

**Comment by victor--** [comment]
Tror att även här är det indexeringsspöket som är i farten. Vi kikar igen på måndag :)
