### ISSUE TITLE
55692 Åtgärdsområde sök

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#170]
Söker på ett åtgärdsområde enligt Coa
Mörrumsån - AREA00448
http://develop.vattenmyndigheten.local/Measures/EditMeasure.aspx?measureEUID=VISSMEASURE0094702

![image](https://cloud.githubusercontent.com/assets/11041042/9250851/54d95182-41d0-11e5-9b58-52ed59c0dd2c.png)

**Comment by idaber** [comment]
Ska dessa vara sökbara? borde de vara eller tänker jag fel?

![image](https://cloud.githubusercontent.com/assets/11041042/9250885/90920db8-41d0-11e5-8a77-2018fb767268.png)

**Comment by victor--** [comment]
Tror det kan vara bra om de är sökbara. Dock kan det vara bra att de kräver en exakt matchning (så man inte söker på "AREA0" och matchar varenda åtgärd i hela VISS).

Ska se om jag kan fixa så att de bara dyker upp med exakta matchningar

**Comment by idaber** [comment]
Detta tas i Fas 2  - får ligga en framtida förbättring

**Comment by idaber** [comment]
Viss ideas
