### ISSUE TITLE
Län och Ansvarigt län  i förbättringsbehovsexporten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#172]
Hämtar län bara? Borde kanske vara specat på två kolumner Län och Ansvarigt län? Sökt på SE623533-149394 i fritextsök. Enligt Henrik verkar Ansvarigt län vara viktigast. Frågan är om båda eller ansvarigt län? Jag tycker båda, dvs bara lägga till en kolumn till + vattenkategori kolumn

![image](https://cloud.githubusercontent.com/assets/11041042/9270790/c014bb7c-4274-11e5-81b1-e0f16390ee1c.png)

![image](https://cloud.githubusercontent.com/assets/11041042/9270794/c9cdec60-4274-11e5-9211-a7cd7debc3ad.png)

**Comment by victor--** [comment]
Precis som Martin skrev i ärendet i serviceportalen är det info om när FB:et skapades/uppdaterades som är relevant (se rutan längst nere till höger [här](http://develop.vattenmyndigheten.local/Improvements/EditImprovement.aspx?improvementEUID=VISSIMPROVEMENT0000002))

**Comment by idaber** [comment]
ok :-)
