### ISSUE TITLE
55398 - saknar urval

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#173]
saknar Delavrinningsområde:

![image](https://cloud.githubusercontent.com/assets/11041042/9272642/eaa95c48-4284-11e5-8009-528f9569b9a2.png)

saknar Påverkan/Pressures + inkludera underliggande

![image](https://cloud.githubusercontent.com/assets/11041042/9272720/94e5d02e-4285-11e5-86cb-3d8415717fa5.png)

ändamålsflaggor:

![image](https://cloud.githubusercontent.com/assets/11041042/9272815/6c26243a-4286-11e5-9974-836cafe1aa3f.png)

Arbetsflaggor:

![image](https://cloud.githubusercontent.com/assets/11041042/9272998/2dd80c50-4288-11e5-8f3c-f9039afe279c.png)

Datumfilter saknas

![image](https://cloud.githubusercontent.com/assets/11041042/9272915/58c1266e-4287-11e5-827b-fee0987afc28.png)

Vattenkategori saknas:

![image](https://cloud.githubusercontent.com/assets/11041042/9272980/f8256aa8-4287-11e5-860e-65b71e993f08.png)

**Comment by victor--** [comment]
Hoppsan, jag måste glömt att inkludera lite filter då jag testade utan att logga in.

Jag har lagt till allt utom delavrinningsområde då den bortgår i o m den nya designen.

Vattenkategori finns, men är flyttat längst upp bland de effektvattenrelaterade filterna :)

**Comment by idaber** [comment]
hur är det tänkt med flaggor och datum? För det ser jag inte nu?

**Comment by victor--** [comment]
Nu så! Tredje gången gillt. Victors minne = :trophy: :fish:

**Comment by idaber** [comment]
Bra jobbat ;-)
