### ISSUE TITLE
Miljöproblem/Påverkan - klassning - kan vi slå ihop filter?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#174]
Kan vi göra på samma sätt - för det känns som vi blandar samma slags filter:

![image](https://cloud.githubusercontent.com/assets/11041042/9379391/21b5ef96-4729-11e5-8c5d-708ef25b2b54.png)
http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=7&export=ExportPluginsExportPluginsImprovementsExport

![image](https://cloud.githubusercontent.com/assets/11041042/9379407/35dcdbd8-4729-11e5-9110-9c8057392656.png)
http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=8&export=ExportPluginsExportPluginsMeasureExportsMeasureExport

Kanske vi kan ge det ett annat namn eftersom det är påverkan i filtret också?
![image](https://cloud.githubusercontent.com/assets/11041042/9379455/963cf828-4729-11e5-9165-2a8fa68b9e7f.png)
http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=8&export=ExportPluginsExportPluginsMeasureExportsMeasureExport

Går det ex att slå ihop filter Miljöproblem och Effektvattenfilter? Vill man inte att det ska specas per vattenkategori behöver man inte välja det?

**Comment by victor--** [comment]
Efter samtal med Henrik: Grabbarna VISS kommer fram till ett förslag på ett filter som fungerar för samtliga exporter. Det har varit prat om att ändra på miljöproblemens struktur, så det faller sig nog naturligt an att låta dem komma fram till en lösning.

**Comment by victor--** [comment]
Stänger detta då jag skapat ett issue på viss-ideas: https://github.com/victor--/viss-ideas/issues/3
