### ISSUE TITLE
56065 - Förbättringsbehovsimport

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#177]
Förstår att texten är generell för alla men i denna kommer de aldrig att kunna importera nya förbättringsbehov (görs i Skapa förbättringsbehov - importen). Kanske blir svårt att ha fler varianter på text?

![image](https://cloud.githubusercontent.com/assets/11041042/9575548/e63496d8-4fd0-11e5-8927-a038353000f7.png)

**Comment by victor--** [comment]
Yes, detta fixar vi i samma veva som jag gör stylingen :)

**Comment by samboman** [comment]
Enligt @victor--

**Comment by victor--** [comment]
Denna är wontfix eftersom att texten inte är generell, utan specifik för förbättringsbehovsimporten.

Det ska gå att skapa nya FB ifall man inte har med ID-nummer i importfilen.
