### ISSUE TITLE
56065 - Statusklassning Miljöproblem grundvatten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#181]
tabellen saknar data

Ex:
![image](https://cloud.githubusercontent.com/assets/11041042/9603447/289e94b6-50b1-11e5-8f99-bc0fc887f6c3.png)

Ex:
![image](https://cloud.githubusercontent.com/assets/11041042/9603464/37d6ff9a-50b1-11e5-89cb-385ddfcb8f97.png)
http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=gwImpacts

**Comment by samboman** [comment]
Jag har testat men kan inte reproducera denna bug. Troligtvis har den fixats av någon annan korrigering till tabellerna.

**Comment by samboman** [comment]
Såg dock att tabellen såg konstig ut, så jag tog bort kolumnen "Påverkanskällor" som hamnart där av misstag.

**Comment by idaber** [comment]
saknar tabellen helt här? se #180

**Comment by idaber** [comment]
ok
