### ISSUE TITLE
56065 - Statusklassning Miljöproblem Ytvatten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#182]
Händer inget när jag klickar på "Visa alla 19 rader"

![image](https://cloud.githubusercontent.com/assets/11041042/9603683/aa9d0848-50b2-11e5-8779-0d14910658da.png)

http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=swImpacts

**Comment by idaber** [comment]
saknar tabellen

**Comment by idaber** [comment]
Fick följande fel när jag skulle ladda upp filen, om något var fel i felen borde jag felmeddelandet vilka rader som inte går att läsa in?

![image](https://cloud.githubusercontent.com/assets/11041042/10015599/95de7c8c-6121-11e5-8bc5-18a6be795c98.png)

**Comment by samboman** [comment]
Denna fixades av en annan fix...

**Comment by idaber** [comment]
ok
