### ISSUE TITLE
Import schemaläggning - skriv ut sidan - saknar funktionalitet

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#183]
Varför vill jag skriva ut denna sidan?

![image](https://cloud.githubusercontent.com/assets/11041042/9603736/05b810ba-50b3-11e5-9111-7f1ab626f3a7.png)

![image](https://cloud.githubusercontent.com/assets/11041042/9603743/178cdcf8-50b3-11e5-82ee-433643de1642.png)

**Comment by victor--** [comment]
Jag stänger denna. Felbeskrivningen, som jag förstår den, är att vi saknar funktionalitet gällande utskiftens form/funktion, vilket jag inte håller med om.
