### ISSUE TITLE
56065 - Statusklassning - styling felmeddelandet

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#184]
Styla?

![image](https://cloud.githubusercontent.com/assets/11041042/9604050/3993d9e4-50b5-11e5-845a-06e73579b42f.png)

**Comment by victor--** [comment]
Kanske i framtiden. Det går utanför detta ärendets räckvidd, skulle jag vilja säga.

Motivation: listan med fel (som du gulmarkerat i skärmdumpen) har alltid haft vanlig brödtext. Detta för att det kan vara väldigt många fel, och det då blir svårläst om man ökar upp teckenstorleken till rubrikernas nivå.

Eventuellt skulle vi i framtiden kunna göra en särskil vy vid de fall att ingenting kunde hittas att importeras.
