### ISSUE TITLE
56065 Statusklassning Parameterbedömning Ytvatten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#186]
Excelfil med 4 fel borde inte ge detta felmeddelande?

![image](https://cloud.githubusercontent.com/assets/11041042/9604924/b9be834e-50ba-11e5-9e96-ef1aa8bf2f40.png)

Fil finns i slack Ekot

http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivation

**Comment by samboman** [comment]
Detta fel kan jag inte reproducera. Frågan är om det är lokalt i din dator / någon låst fil... Vi kan testa på din dator @idaber !

**Comment by idaber** [comment]
Tror att jag hade många filer igång samtidigt här
