### ISSUE TITLE
56065 Statusklassning Parameterbedömning Ytvatten - tabellen försvinner

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#187]
![image](https://cloud.githubusercontent.com/assets/11041042/9605042/955a1012-50bb-11e5-8a65-5319893d80d6.png)
http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivation
Fil i slack

**Comment by samboman** [comment]
Skalade bort ett antal kolumner, så att det visas en "översikt" likt andra importer vi gjort.

**Comment by idaber** [comment]
saknar tabell
