### ISSUE TITLE
56065 Statusklassning Påverkan Grundvatten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#188]
Tabellen visar ingen alls data?

![image](https://cloud.githubusercontent.com/assets/11041042/9605402/d696f78c-50bd-11e5-8380-724a0f22646f.png)
http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=gwPressures

**Comment by idaber** [comment]
saknar tabell

**Comment by victor--** [comment]
Lyckas inte återskapa detta. Kan du prova på nytt, och visa mig om ingen tabell dyker upp?

**Comment by idaber** [comment]
ok
