### ISSUE TITLE
56060 Referenser - saknar schemaläggning

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#190]
![image](https://cloud.githubusercontent.com/assets/11041042/9606927/7848d3d6-50c6-11e5-98d6-3cd8c4f6130c.png)
http://develop.vattenmyndigheten.local/Dialogs/ImportReferences.aspx

**Comment by victor--** [comment]
Skulle gissa på att detta beror på att man vill kontrollera eventuella dubbletter...

Kan @EsleEnoemos bekräfta/förneka? :)

**Comment by EsleEnoemos** [comment]
Kan bekr�fta att det saknas
Enda anledningen att schemal�ggningarna uppfanns fr�n b�rjan, och enda anledningen att anv�nda dom idag, �r f�r importer/exporter som tar f�r l�ng tid f�r att kunna hanteras i en "request" (pga timeouter etc)
Import av referenser har aldrig fallit in under detta eftersom det i de fall den anv�nds handlar om relativt f� poster, samt att importen i sig �r ganska enkel och snabb
Dessutom �r enda anledningen att skapa referenser att man vill anv�nda dem i n�got sammanhang, tex i en parameterbed�mning. Att d� schemal�gga importen inneb�r att man m�ste v�nta en ok�nd tid tills importen �r klar, f�r att sedan hitta referensernas ID, f�r att sedan ange dessa i bed�mningen... vilket inte g�r hanteringen speciellt enkel
Om VISS-centrum verkligen vill ha schemal�ggning av denna import s� �r det bara att be dom best�lla det, i annat fall k�nns den ganska meningsl�s

 //Jakob
Sent from Jakobs iPhone

On 2 sep 2015, at 11:42, Victor Olsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #190<https://github.com/victor--/viss-bugs/issues/190> to @EsleEnoemos<https://github.com/EsleEnoemos>.

-

**Comment by victor--** [comment]
Det köper vi. Stänger ärendet.
