### ISSUE TITLE
56065 Importera bild - tabell?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#193]
Tabell?

Saknar även knappen Genomför Import här. Bilden blir importerad direkt här, varför specar vi denna import annorlunda mot de andra? 

![image](https://cloud.githubusercontent.com/assets/11041042/9680671/b1c43658-52f8-11e5-827d-f87e36893c87.png)

**Comment by samboman** [comment]
Denna import skiljer sig mycket från de övriga, därför får den vara som den är.
