### ISSUE TITLE
Bedömning saknas kommer ut flera gånger på påverkan SW

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#197]
På följande modul och bedömning på påverkanskällor kommer "Bedömning saknas" ut tre gånger

WaterCharacteristics.PageModules.WaterPageModules.SWPressureModule (Påverkan ytvatten)

![image](https://cloud.githubusercontent.com/assets/11041042/9953913/2195a6d2-5de5-11e5-916c-d79778057122.png)

**Comment by EsleEnoemos** [comment]
Fortfarande?

**Comment by idaber** [comment]
kan inte återskapa
