### ISSUE TITLE
Vad gör denna flagga? Använd för MeasuresEcosystemDependingImpact

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#198]
![image](https://cloud.githubusercontent.com/assets/11041042/9955538/1b34b050-5df2-11e5-831b-64916ba8c36d.png)

**Comment by idaber** [comment]
Här?

![image](https://cloud.githubusercontent.com/assets/11041042/9955668/2b691852-5df3-11e5-83aa-23cf6ac2b63b.png)

**Comment by EsleEnoemos** [comment]
Fråga 1: Anger att klassningen ska gå att använda på de olika typerna av P/I, i detta fall ekosystemsberoende miljöproblem

Fråga 2: Vad..?
