### ISSUE TITLE
56235 - kan inte översätta intern beskrivning på  MeasuresEcosystemDependingImpactTypeSpecifications     

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#199]
Jag provade att stänga fönstret och då kunde jag fylla på men problemet kommer åter när jag lägger till info/översättning på en annan specificering

![image](https://cloud.githubusercontent.com/assets/11041042/9955743/bf9740e4-5df3-11e5-8485-17d851a06d76.png)

MeasuresEcosystemDependingImpactTypeSpecifications

**Comment by EsleEnoemos** [comment]
Detta är tyvärr ett känt IE-problem
Har att göra med XSS, och det går att få bort genom att stänga av den inställningen i IE... det är tyvärr enda lösningen :-(
