### ISSUE TITLE
Ser inte möjligheten att välja en referens

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#2]
Jag står på Tvällenområdet. Jag klickar på Redigera vid Allmän beskrivning

![snap5](https://cloud.githubusercontent.com/assets/5877295/5972777/6e288cda-a85f-11e4-8b86-5acfd04d10f2.jpg)

Därefter klickar jag på Skapa ny. Jag väljer att jag vill Lägga till referens. Jag söker på Emån. I träfflistan ser jag inte bockrutorna. Såg inte att det fanns en scrollist förrän du sa det till mig så risken är att de andra handläggarna inte heller ser det. Ohc när de väl ser det blir detta ett irritationsmoment att de varje gång måste scrolla till vänster för att kunna välja

![snap4](https://cloud.githubusercontent.com/assets/5877295/5972796/b3db00c8-a85f-11e4-86ed-71a94b9b6a2e.jpg)

**Comment by victor--** [comment]
Vi har ändrat så modaler alltid tar upp ~90% av den tillgängliga skärmbredden. Bör lösa problemet så länge man inte har väldigt låg horisontell upplösning.

**Comment by PernillaA** [comment]
ok
