### ISSUE TITLE
56235 - Åtgärdssök Inkludera underliggande påverkan/miljöproblem saknas funktion nu snart

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#203]
De underliggande kommer bli specificeringar istället?

Borde egentligen vara på Specificeringar? De kanske du vill inkludera i söket?

![image](https://cloud.githubusercontent.com/assets/11041042/9993328/6c5936e0-6077-11e5-81c7-96c595fee31e.png)

**Comment by EsleEnoemos** [comment]
Det är nåt dom får beställa...
