### ISSUE TITLE
56235 - Export Measure - specificering - visa alla 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#205]
Klickar jag i bocken ex. 
"Inkludera underliggande Påverkan på ytvatten" så borde alla specificeringar kopplade till ex. 1. Punktkällor  + alla underliggande  - komma fram i rullistan under Specificering

![image](https://cloud.githubusercontent.com/assets/11041042/10040006/f19d78c8-61d7-11e5-990f-365a6e10dd3e.png)

**Comment by EsleEnoemos** [comment]
Specificeringen gäller endast den P/I du har valt
