### ISSUE TITLE
56235 - kan vi definiera vad P och PI står för någonstans här? 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#207]
Det kanske bara är Måns inne nu men om det skulle vara fler i framtiden känns det bättre att vara tydlig redan nu :-)

![image](https://cloud.githubusercontent.com/assets/11041042/10067001/b90758a0-6298-11e5-9975-7d0772cf7b76.png)

**Comment by EsleEnoemos** [comment]
Duger inte den mouse-over som finns där...?

**Comment by idaber** [comment]
När jag nu visste om att den fanns, men kan vi göra den tydligare? Jag uppfattade den bara som fet/svar text
