### ISSUE TITLE
56235 - åtgärder PI - modulen som är inställd på en äldre cykel försvinner när jag ska redigera

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#211]
![image](https://cloud.githubusercontent.com/assets/11041042/10074675/9cad56f8-62d1-11e5-8b0a-88654b2a7306.png)

Borde vi inte även här har den röda penna eller varför har vi valt att göra dem olika?

När jag tryckt redigera ser det ut så här istället:

![image](https://cloud.githubusercontent.com/assets/11041042/10074777/33d8db7e-62d2-11e5-8d06-d193c88d013e.png)

modulen är helt borta

**Comment by EsleEnoemos** [comment]
Beror på inställning av vilka moduler som är kopplade till åtgärdskategorin.
När en åtgärd redigeras är det endast de moduler som är kopplade till åtgärdskategorin som visas, INTE de som är valda i någon profil.
Valen i profilerna används enbart vid uppvisning, inte redigering

**Comment by idaber** [comment]
ok
