### ISSUE TITLE
56684 - kan importera trots att parameter inte är med i aktiv cykel

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#224]
![image](https://cloud.githubusercontent.com/assets/11041042/11368208/aed880f2-92b8-11e5-9ce3-4bc9ed3675e3.png)
http://develop.vattenmyndigheten.local/Admin/Default.aspx?section=Parameters&parameterID=418&sortBy0#filter=syn

![image](https://cloud.githubusercontent.com/assets/11041042/11368223/c535ecc2-92b8-11e5-8065-73c09dbeb3b7.png)
http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivation

**Comment by idaber** [comment]
[Export_2015-11-24_14-18-16-347 v2.xlsx](https://github.com/victor--/viss-bugs/files/42751/Export_2015-11-24_14-18-16-347.v2.xlsx)

**Comment by idaber** [comment]
Verkar dock inte gälla parametrar för grundvatten...
http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivationTrends

http://develop.vattenmyndigheten.local/Waters.aspx?waterEUID=SE628995-153160#pagemodule68

![image](https://cloud.githubusercontent.com/assets/11041042/11398575/09b06a7a-9382-11e5-953e-a17fb3473b74.png)


![image](https://cloud.githubusercontent.com/assets/11041042/11398585/1c00a104-9382-11e5-8afc-178c22ec45d2.png)

**Comment by idaber** [comment]
http://develop.vattenmyndigheten.local/ImportClassifications.aspx?importType=waterParameterClassificationMotivationTrends

**Comment by idaber** [comment]
[Export_2015-11-25_14-32-37-720.xlsx](https://github.com/victor--/viss-bugs/files/43888/Export_2015-11-25_14-32-37-720.xlsx)

**Comment by EsleEnoemos** [comment]
Super-användare får alltid klassa, även om parametern inte är med i aktiv cykel
