### ISSUE TITLE
56454 - ignorerar vattenkategori, visar alla

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#228]
![image](https://cloud.githubusercontent.com/assets/11041042/11415825/24ad6126-9408-11e5-927f-2e231a3fa15c.png)
http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=StatisticExport&pluginGuid=01E8EEA2-8F6F-4424-B195-74B949C47238

![image](https://cloud.githubusercontent.com/assets/11041042/11415838/46db8778-9408-11e5-9644-1490fc58af61.png)

**Comment by victor--** [comment]
FYI alla utvecklare: jag löser detta i feature/ParameterMotivationCycles-56684
