### ISSUE TITLE
Obligatoriska uppgifter på sparad export

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#23]
Jag sparar en export. Det finns inget krav på att jag ska välja kategori. 
Jag går sedan in under sparade exporter och vill redigera samma export. Då krävs det att jag väljer en kategori, annars kan jag inte spara mina förändringar. Inkonsekvent. Krav på båda ställena eller inte krav på något ställe.

**Comment by victor--** [comment]
Nu finns kravet på båda ställena.

**Comment by PernillaA** [comment]
ok
