### ISSUE TITLE
56684 Bedömning saknas- checkbox visar ändå bedömningar i vald cykel

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#230]
http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=2&export=ExportPluginsExportPluginsWaterExportsAllWaterParameterMotivationsExport

[Export_2015-12-01_15-39-15-493.xlsx](https://github.com/victor--/viss-bugs/files/48606/Export_2015-12-01_15-39-15-493.xlsx)

http://develop.vattenmyndigheten.local/Waters.aspx?waterEUID=SE626842-147473&timeStamp=1448977002886#pagemodule15

**Comment by idaber** [comment]
samma gäller på denna export:

http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=2&export=ExportPluginsExportPluginsWaterExportsStatusMotivationCompilationExport

ex makrofyter på flaken (samma vatten)
[Export_2015-12-01_16-25-14-663.xlsx](https://github.com/victor--/viss-bugs/files/48675/Export_2015-12-01_16-25-14-663.xlsx)

**Comment by EsleEnoemos** [comment]
Detta är ett känt "problem"...
Filtret "Bedömning saknas" följer med på köpet med de övriga Parameter-filtren, trots att vissa exporter aldrig varit tänkta att ta hänsyn till detta specialfall
Därför struntar dessa exporter helt enkelt i den inställningen
Tyvärr är det inte så enkelt att bli av med just denna checkbox heller, så för tillfället får den vara kvar oförändrad

**Comment by idaber** [comment]
@haseng

**Comment by EsleEnoemos** [comment]
Vad trevligt att få en liten blänkare från VISS :-)
Stackars Hasse om han ska in o gräva i detta...

**Comment by EsleEnoemos** [comment]
:-(

**Comment by victor--** [comment]
:-)
