### ISSUE TITLE
Ny datastruktur - inmatning SWB - felmeddelande

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#233]
Förstår inte vad felet i filen är?

![image](https://cloud.githubusercontent.com/assets/11041042/13110580/404913b6-d581-11e5-89a7-8aa1382a9a29.png)
[gwChemicalExemptionPressure.xlsx](https://github.com/victor--/viss-bugs/files/134328/gwChemicalExemptionPressure.xlsx)

**Comment by idaber** [comment]
samma fel

**Comment by victor--** [comment]
Felet beror på att du har rader det du inte fyllt i samtliga kolumner (rad 7 har t ex bara EUID ifyllt).

Skulle vilja sätta WONTFIX då Måns/Martin med största säkerhet inte kommer fylla i inkompletta rader. Köper du mitt resonemang? :)

**Comment by idaber** [comment]
ok absolut
