### ISSUE TITLE
Ny datastruktur - inmatning SWB - kan inte heller ta bort i firefox

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#234]
![image](https://cloud.githubusercontent.com/assets/11041042/13110765/3a89474c-d582-11e5-8fba-8dd7fddad261.png)
http://develop.vattenmyndigheten.local/WFD2016v601.WaterDataInput/

**Comment by victor--** [comment]
Har samma lösning för FF som för IE nu :see_no_evil:

**Comment by idaber** [comment]
Aha…kolla vad kunden säger..

Från: Victor Olsson [mailto:notifications@github.com]
Skickat: den 18 februari 2016 10:31
Till: victor--/viss-bugs <viss-bugs@noreply.github.com>
Kopia: Ida Bergkvist <ida@meridium.se>
Ämne: Re: [viss-bugs] Ny datastruktur - inmatning SWB - kan inte heller ta bort i firefox (#234)


Har samma lösning för FF som för IE nu [:see_no_evil:]

**Comment by idaber** [comment]
är denna byggd, får samma felmeddelande i firefox när jag trycker ta bort?

**Comment by idaber** [comment]
ok
