### ISSUE TITLE
Havsmiljödirektivet - Lägg till genväg

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#239]
funkar inte 

![image](https://cloud.githubusercontent.com/assets/11041042/13848981/76c293ec-ec54-11e5-93b3-af6eb245e728.png)
http://develop.vattenmyndigheten.local/MarineRegions.aspx?marineRegionEUID=BAL-SE-AA-B_Bottenhavet#

**Comment by idaber** [comment]
Det händer inget när jag klickar...

![image](https://cloud.githubusercontent.com/assets/11041042/14010120/b026cdae-f192-11e5-91ac-e065bba9397a.png)

![image](https://cloud.githubusercontent.com/assets/11041042/14010130/c030d2b2-f192-11e5-80a4-4caf8b19402a.png)
http://develop.vattenmyndigheten.local/MarineRegions.aspx?marineRegionEUID=BAL-SE-RG-Ostersjon#

**Comment by idaber** [comment]
Är denna inlagd på develop, jag kan spara en genväg men när jag laddar om sidan försvinner dem?

**Comment by victor--** [comment]
Ska kika på detta. Hold on!
