### ISSUE TITLE
Exporten för skyddade områden visar fel resultat

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#24]
Detta gäller exporten XVI - vatten - skyddade områden 2014

Jag gör en export för Värmland. Jag väljer att jag vill söka endast med aktiva områden. I filen jag får är det däremot de skyddade områden som är inaktiva. Gör jag samma export fast väljer att jag söka i inaktiva områden får jag däremot rätt, det blir alltså samma fil som om jag väljer "sök endast i aktiva områden".

**Comment by victor--** [comment]
@EsleEnoemos kan du ta denna? :)

**Comment by PernillaA** [comment]
ok
