### ISSUE TITLE
Havsmiljödirektivet - bedömningsområden-funktionell från

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#240]
kan välja områden men kan inte spara områden

![image](https://cloud.githubusercontent.com/assets/11041042/13944672/7a55dea4-f007-11e5-9a29-b0b0fa8edb11.png)

**Comment by haseng** [comment]
Ingen åtgärd... Inställningen ska inte finnas... Och bör nu har försvunnit från Develop.

**Comment by idaber** [comment]
borta
