### ISSUE TITLE
Havsmiljödirektivet - lägg till kopplade havsområden, spara, sen plocka bort några/alla och spara igen

### ISSUE THREAD

**Issue by victor--** [victor--/viss-bugs#243]

**Comment by idaber** [comment]
Nu kan jag inte lägga till nya områden:

![image](https://cloud.githubusercontent.com/assets/11041042/14010054/f7b4800e-f191-11e5-9617-42cd462adbce.png)

**Comment by idaber** [comment]
Felet verkar vara att man när man väljer ett område, tar den det området två gånger:

![image](https://cloud.githubusercontent.com/assets/11041042/14010094/6c1b9c20-f192-11e5-8c6e-43d10e368e51.png)

**Comment by idaber** [comment]
ok
