### ISSUE TITLE
Havsmiljödirektivet - kan inte klicka på länkar till höger

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#244]

**Comment by victor--** [comment]
Verkar som följande havsområde inte vill lira: http://develop.vattenmyndigheten.local/MarineRegions.aspx?marineRegionEUID=BAL-SE-AA-BG_Egentliga_Ostersjon

**Comment by idaber** [comment]
ok, hur går vi vidare? :-)

**Comment by idaber** [comment]
ok
