### ISSUE TITLE
Havsmiljödirektivet - teckensnitt verkar skilja jmfr vatten IE

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#245]
![image](https://cloud.githubusercontent.com/assets/11041042/13979678/55bead36-f0da-11e5-8d4d-4fc4c64594b5.png)

**Comment by victor--** [comment]
Jag har ändrat så den nya kodbasen har bättre kantutjämning (något som inte IE stödjer).

Kan visa er skillnaden jämtemot hur resten av VISS ser ut så kan vi gemensamt fatta ett beslut om hur vi vill att text ska renderas.

**Comment by victor--** [comment]
Stänger denna då vi fått OK på att använda kantutjämning, och då det redan finns på hav-, vatten- och åtgärdssidorna.
