### ISSUE TITLE
Havsmiljödirektivet - dölja vissa kustvatten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#246]
Vissa kustenvattentyper ska inte visas, kan man ha kvar dem i listan Marina områden men dölja dem i listningar?

![image](https://cloud.githubusercontent.com/assets/11041042/13979881/99909c44-f0db-11e5-84f4-29aec98f3be4.png)

![image](https://cloud.githubusercontent.com/assets/11041042/13979892/aa39dcf4-f0db-11e5-95c5-80d2a483b5bd.png)

Kanske här:

![image](https://cloud.githubusercontent.com/assets/11041042/13979906/c353554e-f0db-11e5-965c-92b92da4463f.png)

**Comment by haseng** [comment]
Ny kravspec från Lisa. Vi ska inte mata in rapporteringshavsområden... Därför blir det inte relevant att dölja dom. Det fixas i samband med leverans.
