### ISSUE TITLE
Havsmiljödirektivet - kustvattentyper som ska visas på ett ställe ihop

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#247]
Gäller flertalet kustvattentyp a/b/c

![image](https://cloud.githubusercontent.com/assets/11041042/13980097/dfd1d064-f0dc-11e5-948f-f9a89e325d72.png)

![image](https://cloud.githubusercontent.com/assets/11041042/13980113/f8d0a8c4-f0dc-11e5-858f-b058ab1ff059.png)

Jag kan koppla att de ska rapporteras var för sig men inte att de kan visas som ett område i VISs

**Comment by haseng** [comment]
wontfix.se #246
