### ISSUE TITLE
Meny - rapporteringstatussida

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#255]
när jag ska kolla rapporteringssatussidan hänger inte menyn med riktigt, kan man göra något?

![image](https://cloud.githubusercontent.com/assets/11041042/14381922/3765a210-fd8a-11e5-860f-cc9f6451ea10.png)
http://develop.vattenmyndigheten.local/WFD2016ReportingStatus/

**Comment by idaber** [comment]
Eftersom marinanfliken är borta nu vet jag inte riktigt hur det kommer att se ut ;-)

**Comment by victor--** [comment]
Tror det kommer att fortsätta se bra ut; marinanfliken var ju trots allt bara en temporär lösning. Stänger ärendet :)
