### ISSUE TITLE
Krav från HAV - byta namn på Typ Modul?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#257]
![image](https://cloud.githubusercontent.com/assets/11041042/14599658/eaa81594-0558-11e6-9aca-f8496f76aa7b.png)
http://develop.vattenmyndigheten.local/Admin/Default.aspx?section=MarineRegionPageModules&marineRegionPageModuleID=2

**Comment by victor--** [comment]
Det namnet visas bara i admin, så det känns inte så relevant. Sätter WONTFIX så får du stänga ärendet om du håller med :)
