### ISSUE TITLE
Åtgärdsmodul - översättning PDF-förklaring Visas som förklaring i PDF-wizard IE

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#259]
![image](https://cloud.githubusercontent.com/assets/11041042/14740091/8ec2b45a-088c-11e6-9311-2f4f3218d3c8.png)

![image](https://cloud.githubusercontent.com/assets/11041042/14740083/7a17de36-088c-11e6-9503-202585ed5299.png)

**Comment by haseng** [comment]
Enl Victor måste vi skriva om halva VISS för att det ska funka... Ibland funkar det, ibland inte...
