### ISSUE TITLE
57759 - står att jag får importera 12 rader men sedan smäller det

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#260]
Inloggad: peder.eriksson@lansstyrelsen.se

Är här:
![image](https://cloud.githubusercontent.com/assets/11041042/14917801/0fd64e00-0e21-11e6-8081-c9cea9fdcd64.png)

[Export Bedömningstext för parameterbedömning på vatten.xlsx](https://github.com/victor--/viss-bugs/files/242539/Export.Bedomningstext.for.parameterbedomning.pa.vatten.xlsx)

![image](https://cloud.githubusercontent.com/assets/11041042/14917789/033a88c8-0e21-11e6-8b66-c2ff021ba1e5.png)

![image](https://cloud.githubusercontent.com/assets/11041042/14917775/f606fd30-0e20-11e6-8372-b44bc3703168.png)

**Comment by samboman** [comment]
Har egentligen inte med ärendet att göra... Men det är fixat... :)
