### ISSUE TITLE
MKN redigeringsruta - sparar men stänger sig inte i IE11 wind7

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#266]
![image](https://cloud.githubusercontent.com/assets/11041042/18579390/b07ef91e-7bf5-11e6-9e41-42185abbe0fe.png)

**Comment by victor--** [comment]
Kan inte reproducera varken i min virtmiljö eller i BrowserStack.

**Comment by idaber** [comment]
verkar vara något tillfälligt kan inte heller reproducera...
