### ISSUE TITLE
MKN redigeringsruta SFÄ - redigerar två gånger efter varandra och sparar så visas den gröna texten två gånger 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#267]
![image](https://cloud.githubusercontent.com/assets/11041042/18579597/ee3856dc-7bf6-11e6-8e47-53c6b0213d90.png)

**Comment by victor--** [comment]
Du får hemskt gärna skicka steg för att återskapa. :) När det sparas ska redigeraknappen döljas, så det ska inte gå att spara två gånger.

**Comment by idaber** [comment]
Jag klickar Redigera motivering, redigerar texten, trycker spara
Klickar redigera motivering igen, redigerar texten och sparar.
