### ISSUE TITLE
MKN redigeringsrutan -  ska dessa texter verkligen visas samtidigt?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#268]
![image](https://cloud.githubusercontent.com/assets/11041042/18623577/6092d096-7e3f-11e6-9c0d-fc4b46be2b47.png)

När jag kan redigera så borde inte denna visas 
![image](https://cloud.githubusercontent.com/assets/11041042/18623589/82884a50-7e3f-11e6-9ef0-a19dcbfa9a71.png)

**Comment by victor--** [comment]
Enl. kravspec från första iterationen av MKN-motiveringstexter så ska varningstexten alltid visas.

**Comment by victor--** [comment]
Kom på att du kanske själv vill stänga issues, Ida. Öppnar igen :)

**Comment by idaber** [comment]
ok
