### ISSUE TITLE
#496 - Som icke inloggad eller om jag tar bort version i moduler eller lägger till värde som en kolumn

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#276]
Kan vi göra något åt detta?

![image](https://cloud.githubusercontent.com/assets/11041042/19959617/5e29208a-a1a8-11e6-96d0-bb0a916793e9.png)

![image](https://cloud.githubusercontent.com/assets/11041042/19959632/76c44368-a1a8-11e6-8483-3a78d2f3e36e.png)

**Comment by victor--** [comment]
Värde och klassificering visas inte samtidigt i någon modul. Eftersom att fälten är fasta så stödjer inte designen att de båda fälten är valda i samma modul, därav att designen blir lustig.

**Comment by idaber** [comment]
mm okdå stänger ;-)
