### ISSUE TITLE
Blir en extra linje på vatten utan Åtgärdsområdessammanställning

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#279]
![image](https://cloud.githubusercontent.com/assets/11041042/20209411/950eb13a-a7f4-11e6-993b-8bce5164cacb.png)

Jämför hur det ser ut i VISS idag, borde se likadant ut

![image](https://cloud.githubusercontent.com/assets/11041042/20209537/266f4f90-a7f5-11e6-9eab-2e7ebbb2197f.png)
http://viss.lansstyrelsen.se/Waters.aspx?waterEUID=SE717376-145180

**Comment by ThaliaA** [comment]
Detta ska vara åtgärdat nu!
