### ISSUE TITLE
Fel färg på knappen i IE9

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#28]
Färgen på texten blir inte rätt i IE9

![snap2319](https://cloud.githubusercontent.com/assets/5877295/6144699/96f0bf0a-b1da-11e4-828e-78217520ef64.jpg)

**Comment by victor--** [comment]
Det går tyvärr inte ändra färgen på knappar som är satta som inaktiverade i IE<10.

Då budskapet ändå går fram tycker jag vi tar WONTFIX

**Comment by PernillaA** [comment]
ok
