### ISSUE TITLE
Import av bilder har inte nya gränssnittet

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#29]
Så här ser det ut när jag får varning för import av bilder, borde väl få varningen i det nya gränssnittet? Detta är import som bara importerar sig direkt i och för sig, men varningen borde väl ändå ha det nya utseendet?

![snap2320](https://cloud.githubusercontent.com/assets/5877295/6146487/90af10e8-b1ed-11e4-90fc-1abfe8f66e4c.jpg)

**Comment by victor--** [comment]
Har ändrat så bildimporten använder det nya utseendet. Skillnaden blir att vid lyckad import så visar vi inte slutför import-knappen + att vi byter frasering från "X rader kan importeras" till "X rader *har* importerats".

**Comment by PernillaA** [comment]
ok
