### ISSUE TITLE
den verkar sortera bort skyddade områden när jag väljer cykel 2 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#290]
Jag är här:
http://develop.vattenmyndigheten.local/Exports.aspx?pluginType=&pluginGuid=486d8d1e-77c3-491f-880f-882cd9bf824f&exportCategory=6&export=ExportPluginsExportPluginsAdministrativeExportsProtectedAreaExport2014

Gör dessa val:

![image](https://cloud.githubusercontent.com/assets/11041042/20385984/e62b979e-acb9-11e6-8c86-90c8c41271d3.png)

Jag får ut denna export
[Kopia av Export_2016-11-17_11-31-20-220.xlsx](https://github.com/victor--/viss-bugs/files/597088/Kopia.av.Export_2016-11-17_11-31-20-220.xlsx)

Jag borde få fram detta skyddade området:
http://develop.vattenmyndigheten.local/ProtectedAreas.aspx?protectedAreaEUID=SECM002

![image](https://cloud.githubusercontent.com/assets/11041042/20386065/364737c4-acba-11e6-957e-62ffbfdaa568.png)

**Comment by haseng** [comment]
Området kommer inte med pga att kopplingarna mellan detta område och vatten för Cykel 2 är flaggade som "inaktiva". Om du byter till Cykel 1, så kommer området med i exporten.
