### ISSUE TITLE
Modul skyddade områden på vattensidan -  kan vi snygga till och kanske dra ihop?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#293]
![image](https://cloud.githubusercontent.com/assets/11041042/20473526/9bca2bc4-afc1-11e6-873c-be7e866fbef0.png)

![image](https://cloud.githubusercontent.com/assets/11041042/20473544/af15f1b8-afc1-11e6-84a8-e00648e1c4ef.png)

![image](https://cloud.githubusercontent.com/assets/11041042/20473556/c5a136fe-afc1-11e6-8052-04be181142ff.png)

**Comment by victor--** [comment]
Håller med om att det behöver göras, men det är nog utanför scopet för ärendet. Kan vi tagga detta som att vi åtgärdar det senare, om vi hinner med det?
