### ISSUE TITLE
Ingen snygg popup gällande åtgärdsområde

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#30]
På stationen klickar jag på välj åtgärdsområde

![snap2321](https://cloud.githubusercontent.com/assets/5877295/6164404/2c3fcc4e-b29f-11e4-9257-6157a33f6827.jpg)

Pop-uprutan som öppnas ser inte ut som nya designen

![snap3](https://cloud.githubusercontent.com/assets/5877295/6164413/44e25b22-b29f-11e4-9891-3f1205cb9a46.jpg)

**Comment by victor--** [comment]
Nu har den fått sig ett litet facelift :)

**Comment by PernillaA** [comment]
ok
