### ISSUE TITLE
skyddade område på MKNmodul - får databasfel när jag klickar på området

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#302]
http://develop.vattenmyndigheten.local/Waters.aspx?waterEUID=SE628427-147374

develop är inställd på Cykel 3 som aktiv.

Klickar på det skyddade området:
![image](https://cloud.githubusercontent.com/assets/11041042/20559535/41e44cce-b175-11e6-846b-c5370b706923.png)

skickar felmeddelande till slack/Viss/standup

**Comment by haseng** [comment]
Felet uppstår pga att det inte finns nån data för det skyddade området (och inte för några andra områden heller) i C3! När det är dags att göra C3 till aktiv C, så scriptar vi över all data från C2 till C3. Så det här kommer alltså aldrig att uppstå "på riktigt".

**Comment by idaber** [comment]
Ok vad bra ??

Skickat fr�n min iPhone

23 nov. 2016 kl. 14:13 skrev haseng <notifications@github.com<mailto:notifications@github.com>>:


Felet uppst�r pga att det inte finns n�n data f�r det skyddade omr�det (och inte f�r n�gra andra omr�den heller) i C3! N�r det �r dags att g�ra C3 till aktiv C, s� scriptar vi �ver all data fr�n C2 till C3. S� det h�r kommer allts� aldrig att uppst� "p� riktigt".

-
