### ISSUE TITLE
Jag kan redigera bedömning men den visas inte inne på ett skyddat område

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#304]
Jag har inställt på att cykel 3 ska vara aktiv.

Jag väljer att visa cykel 2 på det skyddade området

pennan är blå, jag är inloggad som ida@meridium.se (superadmin) jag borde få ändra bedömningen i en annan cykel har jag för mig än den som är aktuell?

![image](https://cloud.githubusercontent.com/assets/11041042/20561240/ed6fa5e0-b17d-11e6-91f1-4c7c6ca0d3a9.png)

När jag skapar en ny bedömningen syns den inte i gränssnittet men jag upplever att den sparas som vanligt.

**Comment by haseng** [comment]
Nu sparas motiveringarna i vald Cykel. Och i dialogen visas tidigare motiveringar för vald cykel. Tidigare var dialogen inställd på **aktiv** cykel. Men frågan är om man ska kunna editera motiveringar överhuvudtaget om man står på en annan än **aktiv** cykel... Får väl vara så här tillsvidare...

**Comment by haseng** [comment]
Kontraorder från Henrik, Ida! Vi ska bara kunna redigera kopplingar mellan vatten och PAs för **aktiv** cykel.
