### ISSUE TITLE
Nya fälten finns med även i importen

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#31]
De nya fälten har kommit med även i importen. När jag väljer "ladda ner mallen" så finns de där längst till höger. Testade att mata in uppgifter där men det fungerar ju inte utan den tar givetvis mina inloggningsuppgifter. Men ska de nya fälten verkligen vara med här då, blir ju lite förvirrande för användaren .

![snap3](https://cloud.githubusercontent.com/assets/5877295/6186145/387d8e24-b376-11e4-852f-9b1072b54be7.jpg)

**Comment by victor--** [comment]
Har ändrat så även huvudcellerna har grå bakgrund, så nu är det konsekvent med övriga mallar.

Är lite fräck och stänger detta issue direkt (skäll gärna ut mig om du tycker jag gjort fel!)
