### ISSUE TITLE
Inte nya designen på alla pop-uprutor

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#35]
Jag står på att skapa en åtgärd. Jag väljer plats. Då ser det ut som nedan. Skickar med två bilder. För vatten är det halvt om halvt nya designen, den räcker inte över hela pop-upen och det är en grön avbrytknapp

För övriga "typer" är det inte ny design alls. 

![snap2328](https://cloud.githubusercontent.com/assets/5877295/6227597/3e32eb00-b6a2-11e4-8b65-5093bf81b99d.jpg)

![snap2329](https://cloud.githubusercontent.com/assets/5877295/6227601/41b87b00-b6a2-11e4-8c44-2507a47302bb.jpg)

**Comment by victor--** [comment]
Vi har fixat så vattensöket inte ser trasigt ut längre. Får se om vi hinner med att styla om resterande typer inför morgondagens leverans.

Kanske vi kan stänga detta issue om vattensöket går igenom test, och i samband med det lägga om en issue om att de olika "typerna" inte är omdesignade?

**Comment by PernillaA** [comment]
ok, lägger upp en ny issue
