### ISSUE TITLE
Felaktigt beteende på popup-rutor i chrome

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#36]
Jag redigerar ett program. 
Jag öppnar redigeringen för kvalitetsgranskad

![snap2330](https://cloud.githubusercontent.com/assets/5877295/6228386/9c7659c8-b6ab-11e4-9631-80b43cf3b5ab.jpg)

När jag sparar får jag frågan om jag verkligen vill lämna sidan. Så beter den sig inte i IE9. 

![snap2331](https://cloud.githubusercontent.com/assets/5877295/6228420/0004a30a-b6ac-11e4-8799-dc2ed3cc325f.jpg)

**Comment by victor--** [comment]
Problemet var att den underliggande sidan laddades om när man sparade en kvalitetsgranskning.

Har ändrat så vi istället för att ladda om sidan uppdaterar kvalitetsgranskningen via JavaScript, utan att ladda om sidan (vilket i sin resulterar i att varningsrutan om att lämna sidan aldrig uppstår).

**Comment by PernillaA** [comment]
ok
