### ISSUE TITLE
Visar som om det finns något att läsa trots att det är tomt i fältet

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#4]
Jag är på Tvällenområdet. Under miljökvalitetsnorm finns Kemisk status grundvatten. Det ser ut som om jag har något att läsa under Kvalitetskrav eftersom jag har en pil som jag kan fälla ut, men när jag fäller ut den är det tomt. Om det är tomt borde inte "fälla ut"-pilen finnas.

![snap6](https://cloud.githubusercontent.com/assets/5877295/5972889/2d3cf24a-a861-11e4-879b-e2c390d904d1.jpg)

![snap7](https://cloud.githubusercontent.com/assets/5877295/5972890/300be3be-a861-11e4-91f1-f16a1f20a139.jpg)

**Comment by idaber** [comment]
ok
