### ISSUE TITLE
Gammal design för popup-ruta vid redigering av övervakningsprogram

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#40]
Jag vill lägga till ansvarig organisation för övervakningsprogram. Får felaktig design på pop-uprutan

![snap2333](https://cloud.githubusercontent.com/assets/5877295/6228644/d6bdffa2-b6ae-11e4-92ac-5587aa983940.jpg)

**Comment by idaber** [comment]
Stänger denna nu :-)
