### ISSUE TITLE
Cross site scripting på åtgärder

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#43]
Skriver in felaktig kod i fritextfält för finansieringskällor på en åtgärd, sidan kraschar

Gäller även samarbetspartners, synnergieffekter, miljömålskoppling, hinder, klimatbedömning, miljöindikatorer

**Comment by PernillaA** [comment]
FF samma fel

**Comment by victor--** [comment]
My bad! Bättre nu? :)

**Comment by idaber** [comment]
OK

**Comment by idaber** [comment]
ok
