### ISSUE TITLE
Välja plats för åtgärd, inte stylade pop-uper

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#46]
Jag står på en åtgärd. Jag ska välja plats. Det är bara vatten som är stylat, de andra alternativen är inte stylade.

**Comment by idaber** [comment]
Ska denna göras klart?
![image](https://cloud.githubusercontent.com/assets/11041042/6725874/16c08ef8-ce10-11e4-9fcd-3b662579cf12.png)

**Comment by victor--** [comment]
@idaber: Vi har inte data för biotoper i VISS, så denna kan inte slutföras. Man kan nog ändå tycka att det är oklart att den vyn inte är klar av den anledningen, men då handläggarna har koll på detta kommer denna vyn aldrig visas skarpt.

**Comment by idaber** [comment]
OK
