### ISSUE TITLE
Chrome saknar spara knapp inne i åtgärder i admin

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#48]
bla i Hinder, finansiärer, miljöhinder, miljömål, synergieeffekter
![chrome saknar spara knapp](https://cloud.githubusercontent.com/assets/11041042/6372265/2be7f488-bd03-11e4-8cc7-9b32c1656bd5.PNG)

**Comment by victor--** [comment]
Beskrivningsrutan var för bred, vilket resulterade i att resten av sidan flöt ut till höger. Jag gjorde en quick fix och ändrade så den har rätt bredd istället.

**Comment by idaber** [comment]
OK
