### ISSUE TITLE
54933 50 - Schemadokumentation historik tidigare versioner syns inte om det blir för många poster

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#49]
kan inte scrolla ner om det blir för många poster i historiken

![historik kan inte scrolla ner](https://cloud.githubusercontent.com/assets/11041042/6387672/4331308c-bd8f-11e4-852c-9ad73023d652.PNG)

**Comment by victor--** [comment]
Har ändrat så den aktiva noden automatiskt får en skrollist om den inte ryms på skärmen

**Comment by idaber** [comment]
Funkar fortfarande inte IE9 trots cashad om

**Comment by idaber** [comment]
OK
