### ISSUE TITLE
54933 50 - Schemadokumentation historik - Felmeddelande Din kommentar sparades inte

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#50]
Jag förstår inte som användare vad jag har gjort för fel, kan man markera i vilket fält kan jag gjort fel för att förtydliga? kunde tyvärr inte göra en skärmdump på felmeddelandet.
Är det att jag lagt in ett datum som redan har varit?

![din kommentar sparades inte](https://cloud.githubusercontent.com/assets/11041042/6387737/75c2c7bc-bd90-11e4-90a6-04f34fc828e6.PNG)

**Comment by idaber** [comment]
Såg att det inte kom med vad jag skrivit - lägger in den här
![din kommentar sparades inte](https://cloud.githubusercontent.com/assets/11041042/6387820/a40364f0-bd91-11e4-9cea-3f6ea0e73f19.PNG)

**Comment by idaber** [comment]
har provat att skriva Förväntas vara klart 2015-01-01 men då sparas min kommentar som vanligt
![forvantas vara klart datum bakat i tiden](https://cloud.githubusercontent.com/assets/11041042/6387834/0fddab9a-bd92-11e4-898b-4f45874f5253.PNG)

**Comment by victor--** [comment]
Detta beror på att nätverksproblem uppstår så webbläsaren inte kan kontakta servern — ingenting som vi kan styra över alltså.

Det har ingenting med valideringen eller dylikt att göra.

Jag stänger denna issue så får du gärna öppna upp en ny ifall du kan reproducera så felrutan dyker upp gång på gång genom en viss procedur :)
