### ISSUE TITLE
Qtips saknas på sökval - mouse over funkar inte

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#53]
inställning Enkel mouse-over text - är klickbar bara, visar inte texten när jag drar över musen 

![54859 10 - qtips saknas pa sokval](https://cloud.githubusercontent.com/assets/11041042/6438767/8ebc4da8-c0cc-11e4-90d0-561c9c379e30.PNG)

**Comment by idaber** [comment]
Lägger jag till en extern länk så visas den på rätt sätt inte annars.

**Comment by victor--** [comment]
När denna funktionen utvecklades så aktiverades typen "Enkel" genom att bara föra muspekaren över Qtippet. Kunden gillade inte detta beteendet, utan ville att samtliga typer av qtips skulle kräva klick för att aktiveras.

Jag tror det bästa tillvägagångssättet är att prata med kunden igen, och förhoppningsvis byta tillbaka till hover-beteendet. Om detta nekas kan vi istället ändra texten från "(enkel mouse-over text)" till "(utan formatteringsmöjligheter)"

**Comment by idaber** [comment]
Lagt över i Viss ideas
