### ISSUE TITLE
Qtips - extern länk

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#54]
ingen kontroll på om det är en länk eller inte?
![extern lank](https://cloud.githubusercontent.com/assets/11041042/6438885/91d3317c-c0cd-11e4-9c3a-81cee48e2d88.PNG)

**Comment by EsleEnoemos** [comment]
Det är inte en bugg...
Det skulle mycket väl kunna vara så att du vill göra en länk till en fil som faktiskt heter "testlänk", och det kan systemet inte veta

**Comment by idaber** [comment]
ok
