### ISSUE TITLE
Länkning hänger inte med när jag byter mellan favoriter

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#58]
![lankning schema](https://cloud.githubusercontent.com/assets/11041042/6442013/ce735f8e-c0ec-11e4-9ccb-49420b743917.PNG)

**Comment by victor--** [comment]
WONTFIX. Motivering: Det fungerar att ladda en sida via ett bokmärke, samt att stega fram och tillbaka i historiken. Beteendet där flera snabba byten av hashen i URL:en gör att att siten inte laddas om är inte drastisk nog för att motivera att åtgärda, så länge kunden inte specifikt önskar detta.
