### ISSUE TITLE
Saknar rubriker

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#61]
54498
* Som en redaktör vill jag att varje graf ska in ha en rubrik så jag förstår vad dem representerar

För att göra det ännu tydligare skulle det vara bra att lägga till rubriker, förslagsvis, Månad och Antal
![api rubrik](https://cloud.githubusercontent.com/assets/11041042/6524219/988b2c9a-c3f7-11e4-9b08-e7db1d142a5b.PNG)

**Comment by victor--** [comment]
Det har du helt rätt i :) Redo att testas!

**Comment by idaber** [comment]
Snyggt Victor :-)
