### ISSUE TITLE
Ingressotext - inget radbryt i text då blir texten på en lång rad

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#66]
![ingresso inget radbryt - kopia](https://cloud.githubusercontent.com/assets/11041042/6638971/7f381bd8-c98b-11e4-8e74-d4a2df377f5e.PNG)
![ingresso startsida inget radbryt - kopia](https://cloud.githubusercontent.com/assets/11041042/6638972/7f3812e6-c98b-11e4-9ad1-82c03bee318a.PNG)

**Comment by victor--** [comment]
Denna yttrar sig enbart om man ha en teckenföljd på ~100 tecken utan mellanslag. Kommer aldrig inträffa skarpt alltså (om den gör det lovar jag att äta upp min hatt!).

**Comment by idaber** [comment]
OK :-)
