### ISSUE TITLE
FElmeddelande vid schemaläggning av undersökning på övervakningsprogram

### ISSUE THREAD

**Issue by PernillaA** [victor--/viss-bugs#7]
Jag går på Undersökningar på ett övervakningsprogram. Jag väljer ingen fil utan klickar direkt på Schemalägg import. Jag förväntade mig ett fel att jag inte valt någon fil. Men jag får nedanstående

![snap8](https://cloud.githubusercontent.com/assets/5877295/5974679/732b32e2-a877-11e4-937b-e4a8e77be398.jpg)

**Comment by victor--** [comment]
Nu varnar systemet om man försöker importera/schemalägga import utan någon vald fil.

**Comment by PernillaA** [comment]
ok
