### ISSUE TITLE
Mappning text uppdateras inte när jag tar bort datan

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#70]
Om jag tar bort alla inställningar och bockar ur komplett så försvinner den gröna bocken men kvar blir den blå ikonen, trots att jag inte angivit något

![mappning saknar uppdatering](https://cloud.githubusercontent.com/assets/11041042/6640210/05b2d540-c996-11e4-9e2f-bec96b2cc356.PNG)

**Comment by victor--** [comment]
Kunder lär inte "rensa" samtliga fält. Sen kan man resonera att rensad data också är data.
