### ISSUE TITLE
Programområde - tvingande välj minst ett?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#72]
Ska det inte vara tvingande att välja minst ett programområde på övervakningsprogram innan man kan trycka spara?

![programomrade del 1](https://cloud.githubusercontent.com/assets/11041042/6661842/5d0509e8-cbb3-11e4-9033-1e91443692a0.PNG)
![programomrade redigera](https://cloud.githubusercontent.com/assets/11041042/6661843/5d05d0b2-cbb3-11e4-9b0c-ec2c2dcc1042.PNG)

**Comment by idaber** [comment]
Osäker om det är en bug eller inte?

**Comment by EsleEnoemos** [comment]
Du har så rätt :-)
Jag fixar!

**Comment by EsleEnoemos** [comment]
Nu kan du testa igen :-)

**Comment by idaber** [comment]
Ok :-)

**Comment by idaber** [comment]
Funkar inte längre

**Comment by idaber** [comment]
ok :-)
