### ISSUE TITLE
Vid skapande av ny övervakningsstation saknar koppling till karta 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#73]
Borde man inte kunna få möjlighet att välja på en karta direkt härifrån istället för att först hämta koordinaterna från kartan och sedan skriva in dem manuellt?

![overvakningsstation karta](https://cloud.githubusercontent.com/assets/11041042/6662189/9938a6b8-cbb8-11e4-9f2f-843a5439d0df.PNG)

**Comment by victor--** [comment]
Bra frågeställning! :)

Tyvärr finns det inget stöd för detta i Silverlightkartan vi använder oss av då den inte kan kommunicera direkt med webbläsaren på ett sätt som kan förverkliga detta.

Det är nog först när/om vi går över till en HTML5-/JS-karta som detta blir tekniskt möljigt.

**Comment by idaber** [comment]
I framtiden kanske :-)
