### ISSUE TITLE
Hämtar bara en kommun i exporten även om det är registrerat flera kommuner

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#76]
![kalmarsunds utsjovatten](https://cloud.githubusercontent.com/assets/11041042/6708722/40729e64-cd73-11e4-847f-ae952f4ca47f.PNG)
![se565400-163600](https://cloud.githubusercontent.com/assets/11041042/6708721/406f961a-cd73-11e4-81c9-3269d773b873.PNG)

**Comment by idaber** [comment]
Likaså gäller LÄN

**Comment by EsleEnoemos** [comment]
No fix
En koordinat ligger bara i 1 kommun, även om vattnet som kanske har koordinaten kan ligga i flera kommuner...

**Comment by idaber** [comment]
Helt rätt
