### ISSUE TITLE
tvingande filter kontra varning - konsekventa?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#80]
I denna export är det tvingande att med minst ett geografiskt filter + varningen kommer även upp här
![image](https://cloud.githubusercontent.com/assets/11041042/6781386/77755354-d16d-11e4-9d1d-eae70f638c4a.png)

medan resterande exporter med geografiska filter får upp en varning när du inte valt något geografiskt filter

![image](https://cloud.githubusercontent.com/assets/11041042/6781427/d45bd49e-d16d-11e4-8662-b2536f5cd869.png)

Förslag plocka bort denna del för att vara konsekvent?
![image](https://cloud.githubusercontent.com/assets/11041042/6781483/54fa4f36-d16e-11e4-890e-f80b14ed8f2e.png)

**Comment by victor--** [comment]
Skillnaden är väl att rutan som kommer upp är en varning (man kan slutföra exporten om man trycker på bekräftaknappen) medan den rosa rutan är ett krav (du **måste** välja ett av filterna för att exporten ska gå att genomföra).

Om vi tar bort den rosa rutan så måste vi istället ändra varningsrutan så att den stoppar exporten om man inte valt något av de krävda filterna. Då finns det dessutom ingen indikation på att dem faktiskt är ett krav fram till det att man väl tryckt på exporteraknappen.

**Comment by idaber** [comment]
Hur kommer det sig att just denna export är tvingande men ingen annan?

**Comment by victor--** [comment]
Bra fråga. Efter diskussion med kund kom vi fram till att denna exporten ändå inte har använts sen 2008, så vi plockar helt enkelt bort den från menyn så slipper vi problemet med inkonsekvens :)

**Comment by idaber** [comment]
OK :-)
