### ISSUE TITLE
Saknar bokstav Ä i visningsläge på en vattenförekomst

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#82]
http://develop.vattenmyndigheten.local/ProtectedAreas.aspx?protectedAreaEUID=SECM001

Ä syns inte i Goggle Chrome på Vattenförekomsten Bäck vid Ökull

![image](https://cloud.githubusercontent.com/assets/11041042/6799576/4da869d0-d217-11e4-9b48-ae27325368ca.png)

I IE9 syns det som vanligt:
![image](https://cloud.githubusercontent.com/assets/11041042/6799609/8b99c8ba-d217-11e4-9df3-77d306a7cfa8.png)

**Comment by EsleEnoemos** [comment]
Vad händer om du startar om chrome?
Alltså verkligen stänger av ALLA chrome-fönster, och sedan startar ett nytt...?

**Comment by idaber** [comment]
Konstigt fel, tar bort från ärendet och låter ligga kvar som en bug

**Comment by idaber** [comment]
stänger
