### ISSUE TITLE
Rapportmappning saknar länkning 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#84]
Är inne i reporting och sedan WFD2016
Kommer inte åt Rapportmappning när jag klickar på den - felmeddelande

http://develop.vattenmyndigheten.local/WFD2016.Mappings/

![image](https://cloud.githubusercontent.com/assets/11041042/6803732/df596f60-d239-11e4-8984-3b85b94fb194.png)

**Comment by victor--** [comment]
Detta beror på att rapportmappningen inte har samma länk i develop.vattenmyndigheten.local som i skarpa VISS.

Om du ser på http://viss.lansstyrelsen.se/WFD2016.Mappings/ så fungerar länken där.
