### ISSUE TITLE
Avancerat sök Övervakningsbedömningar - filter

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#86]
Är inne i Avancerat sök och väljer Övervakningsbedömningar. När jag inte väljer några filter får jag upp alla bedömningar. När jag däremot använder filtret Land - Sverige kommer bara sökresultat upp för Lortan och Flaken? Jag borde väl få ungefär samma resultat, förutom de norska?
http://develop.vattenmyndigheten.local/Search.aspx?searchType=StationMonitoringProgramMotivations

25 träffar
![image](https://cloud.githubusercontent.com/assets/11041042/6826694/97d98eca-d303-11e4-97d5-da83eff66947.png)

Utan något filter får jag fram bedömningar from bla stockholm och många många fler
![image](https://cloud.githubusercontent.com/assets/11041042/6826887/94dc9bee-d304-11e4-86ab-fd86a009d875.png)

**Comment by victor--** [comment]
Med Idis välsignelse stänger jag denna
