### ISSUE TITLE
Redigera-verktyget Modulsidan Vatten 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#88]
Trots att jag tagit bort att jag inte vill visa modullänkar syns inte knappen "Redigera verktygsinfo" helt.
Den visas inte helt om typ av modul har en text som är för lång?

http://develop.vattenmyndigheten.local/Admin/Default.aspx?section=WaterPageModules&waterPageModuleID=31
![image](https://cloud.githubusercontent.com/assets/11041042/6844511/4e8ccd14-d3ac-11e4-9867-470592aac824.png)

![image](https://cloud.githubusercontent.com/assets/11041042/6844670/5de4de72-d3ad-11e4-81fc-b0b649599fd3.png)

Den försvinner helt när man har aktivt valt att ha med modullänkar ..no good

![image](https://cloud.githubusercontent.com/assets/11041042/6844723/bfa5eeee-d3ad-11e4-86bd-e7d5c89d26de.png)

**Comment by victor--** [comment]
Ska undersöka om man kan lösa detta layoutproblem för samtliga adminsidor utan att behöva ändra i hundratals olika kodfiler. Om så är fallet löser jag det med en gång, om inte behöver kunden skapa ett ärende.

**Comment by victor--** [comment]
Vi gjorde en quick-fix: knappen är nu vänsterställd, så den bör alltid synas nu. Detta är givetvis inte en gedigen lösning; det får bli av när kunden beställer ett ärende för att se över layouten på adminsidorna.

**Comment by idaber** [comment]
ok
