### ISSUE TITLE
Självregistrerande - ska de kunna se mailadress?

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#92]
![image](https://cloud.githubusercontent.com/assets/11041042/6892194/480eeb0c-d6c2-11e4-9885-4496c602c57f.png)

Enligt CoA?
** Kolumnen med email-adress på "bedömmaren" läggs endast till om den som gör exporten är inloggad.

**Comment by victor--** [comment]
Bra fråga. ping @EsleEnoemos :)

**Comment by EsleEnoemos** [comment]
Självregistrerade är per VISS-definition inte inloggade, så svaret är NEJ.

**Comment by idaber** [comment]
Ok vi stänger denna :-)
