### ISSUE TITLE
Saknar vem som gjort versionshanteringen skyddat område vso vatten

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#95]
http://develop.vattenmyndigheten.local/ProtectedAreas.aspx?protectedAreaEUID=SEA7SE629163-146824

![image](https://cloud.githubusercontent.com/assets/11041042/6959266/2d97a12c-d917-11e4-9e19-4f1622db937b.png)

Borde det även synas på Vattenförekomsten under skyddade områden 2014 eller?

http://develop.vattenmyndigheten.local/Waters.aspx?waterEUID=SE626842-147473
![image](https://cloud.githubusercontent.com/assets/11041042/6959300/9937391a-d917-11e4-9a20-6495a57cdfe1.png)

**Comment by victor--** [comment]
Helt rätt — jag var slarvig med att läsa CoA!
Lade till både fält för inläggare samt kontaktlänk.

**Comment by idaber** [comment]
ok :-)
