### ISSUE TITLE
Databasfel? Bedömningar på sök

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#96]
http://develop.vattenmyndigheten.local/Search.aspx?searchType=WaterMotivations&SearchOnLoad=true&LockWaterDataset=&waterTypeID=38&parameterSearchType=1&freeTextSearch=&WaterDataSet=2&ReportUnitSearch=128&SearchAfterDate=&SearchBeforeDate=&countryID=&competentAuthorityID=&areaID=&countyID=&municipalityID=-&basinID=&subUnitID_2=&subUnitID_8=&subUnitID_1=&subUnitID_4=&protectedAreaCategoryID=&userID=&measureGroundWaterPressureTypeID=&gwpressureparameterClassificationID=&measureGroundWaterImpactTypeID=&gwimpactparameterClassificationID=&measuresEcosystemDependingImpactTypeID=&ecoimpactparameterClassificationID=&WaterParameterClassificationMotivationConfidenceIndicatorID=&WaterParameterClassificationMotivationTypeID=&parameterGroupID=&parameterID=&parameterClassificationID=&parameterValueID=&parameterVersionID=&waterParameterClassificationTrend=&extraParametersSearchOption=0&NotClassified=true&DialogMode=&DoSearch=&SortType=1&ReversSort=false&requirePermissionsToSelect=false&searchLockAreas=false&searchLockBasins=false&searchLockMunicipality=false&searchLockWaterType=false&AssociatedWaters=&postbackAction=&searchLockReportUnitSearchTypes=

Val: Grundvatten och Parameter
![image](https://cloud.githubusercontent.com/assets/11041042/7046676/d2cefa38-de07-11e4-9f88-3f6cc0f77c79.png)

**Comment by victor--** [comment]
Detta är en gammal bugg som beror på att du blanksöker vilket gör att datat som ska hämtas från databasen är så omfattande att vi får en timeout.

ping @EsleEnoemos kan vi fixa detta alternativt förbättra UX på något smidigt vis?

**Comment by EsleEnoemos** [comment]
Allt är möjligt för den som har pixelseende :-)

**Comment by idaber** [comment]
ok stänger
