### ISSUE TITLE
Vattenrådsområde , inga val

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#97]
Jag förstår inte varför jag inte kan välja Vattenrådsområde här? Finns det inget för just dessa val, kan vi bara visa den när den är aktuell?

![image](https://cloud.githubusercontent.com/assets/11041042/7061325/a782c42a-de90-11e4-87f2-e79f9728ce21.png)

**Comment by victor--** [comment]
Vet inte om man säkert kan ta bort detta fältet eller om det bara fylls med inlägg om vissa kriterier uppfylls (att man väljer rätt län/kommun/etc)

ping @EsleEnoemos :)

**Comment by EsleEnoemos** [comment]
Det fylls i med alla områden som finns inom de geografier som du har valt, så den går inte att ta bort!
