### ISSUE TITLE
Kryssruta Bedömning saknas Miljöproblem - Ytvatten 

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#99]
Jag förstår inte varför denna ligger längst ner, den borde vara med de i andra i "samma" grupp?

![image](https://cloud.githubusercontent.com/assets/11041042/7061758/ec7fb556-de95-11e4-86a9-501b030dcc5d.png)

**Comment by idaber** [comment]
Försvinner speciellt om man lägger till flera parameterfilter

**Comment by victor--** [comment]
Jo, det stämmer. Tanken var att placeringen av samtliga element i formuläret skulle vara statiska oberoende av vilken söktyp man valt, men jag tror att det nog kan bli bättre om vi flyttar upp checkboxen till där du föreslag de fallen man *inte* väljer parameter som söktyp, men låta den vara kvar där den är om man faktiskt söker efter parametrar.

**Comment by victor--** [comment]
Jag flyttade upp rutan för samtliga olika söktyper. Blir nog mer konsekvent så.

**Comment by idaber** [comment]
Blir man förvirrad tro när man väljer parameter på söktyp eller förstår man vad som händer tror du?

![image](https://cloud.githubusercontent.com/assets/11041042/7082980/2ed8f4e6-df5c-11e4-8601-20af47b68272.png)

**Comment by idaber** [comment]
Vi funderar på om vi kan förbättra denna och finna en bättre lösning :-). Stänger den tillsvidare!
